# Change these first
owner: ayeja153 # Your GitHub organization or username, where this repository lives
repo: websites-checks # The name of this repository

sites:
  - name: UCI
    url: https://www.uci.cu
assignees: # Users to assign downtime issues (optional)
  - ayeja153

status-website: # Status website (optional)
  # cname: upptime.js.org # Custom domain CNAME
  baseUrl: /websites-checks
  name: Upptime # Status website title
  
